### ISSUE TITLE
Migrate to setup-flyctl style action

### ISSUE THREAD

**Issue by btkostner** [superfly/flyctl-actions#12]
Considering how simple this action is, we should consider migrating it to a `setup-` style action similar to how `setup-node`, `setup-elixir`, and a bunch of other actions work.

This would simplify how commands work, and has the added bonus that you can copy straight out of the docs. This would also mean we wouldn't be running commands in a docker container, so things like `flyctl auth docker` would work 👍

**Comment by AlexanderNZ** [comment]
This would be great!
I'm currently integrating Fly into my pipeline and want to build and test my containers separate to deploying them (i.e. only deploy if certain integration tests pass)

Right now I can't do that with this action, because I need to `auth docker`. So instead I'll have to figure out a work around

**Comment by mrkurt** [comment]
This is a good idea. 

@AlexanderNZ you can actually auth to our Docker repository without `flyctl` in the meantime:

```yml
      - name: 🔑 Fly Registry Auth
        uses: docker/login-action@v1
        with:
          registry: registry.fly.io
          username: x
          password: ${{ secrets.FLY_API_TOKEN }}
```

from: https://github.com/kentcdodds/kentcdodds.com/blob/main/.github/workflows/deployment.yml#L194-L199
