### ISSUE TITLE
Build fails with issues running ssh console

### ISSUE THREAD

**Issue by kulor** [superfly/flyctl-actions#13]
This snippet of Github action config has just started failing:

```yml
...
- uses: superfly/flyctl-actions@master
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        with:
          args: "ssh console --command 'sh /app/build/scripts/post_deploy.sh'"
```

with the following error message:

```
sh: console: unknown operand
Error: unknown flag: --remote-only
Error unknown flag: --remote-only


Usage:
  flyctl ssh console [<host>] [flags]

Flags:
  -a, --app string       App name to operate on
  -C, --command string   command to run on SSH session
  -c, --config string    Path to an app config file or directory containing one (default "./fly.toml")
  -h, --help             help for console
  -p, --probe            test WireGuard connection after establishing
  -r, --region string    Region to create WireGuard connection in
  -s, --select           select available instances

Global Flags:
  -t, --access-token string   Fly API Access Token
  -j, --json                  json output
      --verbose               verbose output
```

Running the aforementioned script directly on the CLI `fly ssh console --command 'sh /app/build/scripts/post_deploy.sh'` works as expected (whilst using the latest `flyctl`) so it seems specific to this action.
