### ISSUE TITLE
Build error while deploying 

### ISSUE THREAD

**Issue by alexwebgr** [superfly/flyctl-actions#31]
`fly deploy` works great locally but fails when i am running this action 

i have tried adding `ENV DOCKER_BUILDKIT=1` to the Dockerfile but i still get the same error 

Error failed to fetch an image or build from source: error building: error rendering build status stream: the --mount option requires BuildKit. Refer to https://docs.docker.com/go/buildkit/ to learn how to build images with BuildKit enabled

workflow file
```
name: Fly Deploy
on: [push]
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy
```
