### ISSUE TITLE
Can't find Dockerfile when deploy

### ISSUE THREAD

**Issue by mingchau** [superfly/flyctl-actions#34]
Files contents:

**Dockerfile:**
```
FROM python:3.10
RUN apt-get update && apt-get install -y \
    python3-pip \
    python3-venv \
    python3-dev \
    python3-setuptools \
    python3-wheel

COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .
CMD ["python", "main.py"]
```
**fly.toml**
```
# fly.toml file generated for white-morning-129 on 2023-01-11T20:36:32+08:00

app = "some-appname-129"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

```
**.github\workflows\fly.yml**
```
name: Fly Deploy
on:
  push:
    branches:
      - main
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v3

        - name: Setup Flyctl
          uses: superfly/flyctl-actions/setup-flyctl@master

        - name: List Files in Current Dir
          run: ls

        - name: Deploy App
          run: flyctl deploy
```

**GitHub Repo file structure:**
![image](https://user-images.githubusercontent.com/18564039/211823064-83f5e38f-3ddf-4c01-8750-ba538b0df6d8.png)

**GitHub Actions Log:**
![image](https://user-images.githubusercontent.com/18564039/211823302-de9bcdc9-2ff0-4274-8d0a-2f0cabab5d71.png)
![image](https://user-images.githubusercontent.com/18564039/211823381-b96afabe-ea81-434b-89a2-7e5e9df0d224.png)

**Comment by eliasj** [comment]
Hi!
I tried your fly.yml and it worked for me. 

One difference I could find in your `fly.toml` was that I got this line
```toml
[build]
  dockerfile = "Dockerfile"
```
Maybe that will help

Also, my Dockerfile also looks different, but I'm running a Django app.
```Dockerfile
ARG PYTHON_VERSION=3.10-slim-buster
FROM python:${PYTHON_VERSION}
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
RUN mkdir -p /code
WORKDIR /code
COPY requirements.txt /tmp/requirements.txt
RUN set -ex && \
    pip install --upgrade pip && \
    pip install -r /tmp/requirements.txt && \
    rm -rf /root/.cache/
COPY . /code/
RUN python ./manage.py collectstatic
EXPOSE 8000
CMD ["gunicorn", "--bind", ":8000", "--workers", "2", "mysite.wsgi"]
```

Can you deploy it from your own computer?
