### ISSUE TITLE
change repo primary branch to `main`?

### ISSUE THREAD

**Issue by isaacbowen** [superfly/flyctl-actions#42]
https://www.theserverside.com/feature/Why-GitHub-renamed-its-master-branch-to-main

**Comment by jsierles** [comment]
This is good, but a lot of people are pinned to `master` already. Any idea what would happen if the name is changed?

**Comment by isaacbowen** [comment]
For sure:

* https://github.com/github/renaming
* https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch

If it's _really_ important to keep that ref valid, you could wire up something to keep `master` synced to `main` too.

**Comment by benthecarman** [comment]
there's no reason to do this

**Comment by pboling** [comment]
If we expect the future to contain more projects than the past, and I sure hope it does, then it does make sense to do this.  It is now the default.  So everytime I see a `master` branch reference I am forced to wonder if the documentation is out of date, and go check, adding many minutes of wasted time, every single time I see the term `master`.  Multiple me by millions, and the aggregate cost to humanity is large.  On the other hand the number of projects already using `master` is fixed at every point in time, so there is no better time to switch than now.

**Comment by pboling** [comment]
Additionally, there is a "keep-my-github-actions-up-to-date" dependabot task that should conceivably be made to handle this switch automatically, and send a PR to update.  Not sure if it does as I only just started using it, but it would be a simple feature to add.

```
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
```
