### ISSUE TITLE
Allow using `fly` instead of only `flyctl`

### ISSUE THREAD

**Issue by einarpersson** [superfly/flyctl-actions#44]
Hi!

I just had a problem where I got `fly: command not found`. When I changed to `flyctl` it started working.

In your [official documentation](https://fly.io/docs/) you use `fly` instead of `flyctl` quite a lot. I would therefore recommend that using `fly` would also be OK in workflows using this action. I think it should be consistent with the normal installation (which adds the symlink fly->flyctl).

**Comment by CanRau** [comment]
same just happened to, was confusing as I thought the CLI is moving more towards `fly` instead of `flyctl` so stopped using the latter completely 🥲

**Comment by Igloczek** [comment]
For those who don't want to wait, or just prefer full CLI access, drop it in your workflow config instead of official action, and you are good to go.

```yml
      - name: Install Fly CLI
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "/home/runner/.fly/bin" >> $GITHUB_PATH
```

If you are not using `runs-on: ubuntu-latest` you most likely will need to update the directory that is added to PATH, based on what the setup script will print in logs.
