### ISSUE TITLE
GitHub Actions: periodic `flyctl: not found`

### ISSUE THREAD

**Issue by seeARMS** [superfly/flyctl-actions#57]
We have a GitHub action workflow that deploys our Fly instance upon git push.

Periodically and seemingly randomly, the workflow quickly fails with the following error:

```
Run superfly/flyctl-actions@1.1
  with:
    args: deploy --remote-only --strategy immediate --wait-timeout 360 --config ./packages/api/fly.staging.toml --dockerfile ./packages/api/Dockerfile --ignorefile .dockerignore --app paragraph-feature-par-[2](https://github.com/paragraph-xyz/monorepo/actions/runs/8740055948/job/23982824117#step:5:2)645 -e COMMIT=${GITHUB_SHA} --vm-size shared-cpu-2x
  env:
    FLY_API_TOKEN: ***

sh: flyctl: not found
```

Flyctl should never not be found, so I don't know why this is occurring.
