### ISSUE TITLE
Support FLY_APP environment variable

### ISSUE THREAD

**Issue by ajsharp** [superfly/flyctl-actions#6]
Currently trying to conditionally set the `FLY_APP` environment variable in non-production branches to deploy to a staging environment, but it doesn't look like it's getting picked up:

```yaml
name: Fly Deploy
on: [push]
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set fly app name
        if: ${{ github.ref != 'refs/heads/master' }}
        env:
          FLY_APP: staging-app-name
        run: echo "Setting FLY_APP=staging-app-name"
      - uses: superfly/flyctl-actions@1.1
        with:
          args: "deploy"
        env:
          ANOTHER_VAR: value
```
