### ISSUE TITLE
Action fails after upgrading flyctl version to 0.2.73

### ISSUE THREAD

**Issue by sheerlox** [superfly/flyctl-actions#61]
The action fails without any error log (even in debug mode) since upgrading to [flyctl `v0.2.73`](https://github.com/superfly/flyctl/releases/tag/v0.2.73):

![image](https://github.com/superfly/flyctl-actions/assets/11234273/a2bba913-2af1-4e13-91dd-15a3fbcc1aab)

Workflow file:
```yml
name: Deploy Staging

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

jobs:
  deploy-staging:
    name: Deploy app
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    concurrency: deploy-staging-group
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Create .env file
        run: cp .env.example .env

      - name: Output app revision
        run: make get-revision

      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: 0.2.73 # renovate: datasource=github-releases depName=flyctl packageName=superfly/flyctl versioning=semver

      - run: flyctl deploy --remote-only --config fly.staging.toml -e APP_REVISION="$(make get-revision)"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_STAGING }}
```

Downgrading to `v0.72.2` solves the issue:
![image](https://github.com/superfly/flyctl-actions/assets/11234273/19be4e3f-f850-4974-ab74-1600e929976a)
